# Generated by Django 5.2.3 on 2025-06-23 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('crm', models.CharField(max_length=6, primary_key=True, serialize=False, unique=True, verbose_name='CRM')),
                ('nome', models.CharField(max_length=100)),
                ('especialidade', models.CharField(max_length=100)),
                ('foto', models.ImageField(blank=True, upload_to='fotos/%Y/%m/%d')),
            ],
        ),
    ]
