# Generated by Django 5.2.3 on 2025-06-26 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medico',
            options={'verbose_name': 'Médico', 'verbose_name_plural': 'Médicos'},
        ),
        migrations.AlterField(
            model_name='medico',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='medicos_fotos/', verbose_name='Foto do Médico'),
        ),
    ]
