# Generated by Django 5.2.3 on 2025-07-13 23:58

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medico', '0002_alter_medico_options_alter_medico_foto'),
        ('paciente', '0002_paciente_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(validators=[django.core.validators.MinValueValidator(limit_value=django.utils.timezone.now, message='Data não pode ser no passado')])),
                ('tipo', models.CharField(choices=[('consulta', 'Consulta'), ('retorno', 'Retorno'), ('exame', 'Exame'), ('cirurgia', 'Cirurgia')], default='consulta', max_length=20)),
                ('status', models.CharField(choices=[('agendada', 'Agendada'), ('realizada', 'Realizada'), ('cancelada', 'Cancelada'), ('falta', 'Falta')], default='agendada', max_length=20)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='medico.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='paciente.paciente')),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
                'ordering': ['data'],
                'constraints': [models.UniqueConstraint(fields=('medico', 'data'), name='unique_consulta_medico_data')],
            },
        ),
    ]
